export const PLATFORMS = [
  {
    id: 'linkedin',
    name: 'LinkedIn',
    type: 'Professional',
    iconName: 'linkedin',
    color: '#0A66C2',
    gradientColors: ['#0A66C2', '#064799'],
    charLimit: 2600,
  },
  {
    id: 'instagram',
    name: 'Instagram',
    type: 'Social',
    iconName: 'instagram',
    color: '#E1306C',
    gradientColors: ['#F77737', '#E1306C', '#833AB4'],
    charLimit: 150,
  },
  {
    id: 'twitter',
    name: 'X (Twitter)',
    type: 'Social',
    iconName: null,
    iconText: 'X',
    color: '#000000',
    gradientColors: ['#1a1a1a', '#000000'],
    charLimit: 160,
  },
  {
    id: 'threads',
    name: 'Threads',
    type: 'Social',
    iconName: 'at',
    color: '#000000',
    gradientColors: ['#333333', '#111111'],
    charLimit: 150,
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    type: 'Social',
    iconName: 'music-note',
    color: '#FF0050',
    gradientColors: ['#25F4EE', '#FE2C55'],
    charLimit: 80,
  },
  {
    id: 'youtube',
    name: 'YouTube',
    type: 'Social',
    iconName: 'youtube',
    color: '#FF0000',
    gradientColors: ['#FF0000', '#CC0000'],
    charLimit: 1000,
  },
  {
    id: 'hinge',
    name: 'Hinge',
    type: 'Dating',
    iconName: 'heart-multiple',
    color: '#E63950',
    gradientColors: ['#E63950', '#B02E40'],
    charLimit: 300,
  },
  {
    id: 'bumble',
    name: 'Bumble',
    type: 'Dating',
    iconName: 'bee',
    color: '#FFC629',
    gradientColors: ['#FFD43B', '#FFC629'],
    charLimit: 300,
  },
  {
    id: 'github',
    name: 'GitHub',
    type: 'Professional',
    iconName: 'github',
    color: '#ffffff',
    gradientColors: ['#4a4a4a', '#24292e'],
    charLimit: 160,
  },
  {
    id: 'discord',
    name: 'Discord',
    type: 'Social',
    iconName: 'forum',
    color: '#5865F2',
    gradientColors: ['#7289DA', '#5865F2'],
    charLimit: 190,
  },
  {
    id: 'reddit',
    name: 'Reddit',
    type: 'Social',
    iconName: 'reddit',
    color: '#FF4500',
    gradientColors: ['#FF6534', '#FF4500'],
    charLimit: 200,
  },
  {
    id: 'substack',
    name: 'Substack',
    type: 'Professional',
    iconName: 'newspaper-variant-outline',
    color: '#FF6719',
    gradientColors: ['#FF8C42', '#FF6719'],
    charLimit: 280,
  },
];

export const PLATFORM_BY_ID = Object.fromEntries(PLATFORMS.map((p) => [p.id, p]));
