export const PLATFORMS = [
  // ── Dating ────────────────────────────────────────
  {
    id: 'hinge',
    name: 'Hinge',
    type: 'Dating',
    iconName: 'heart-multiple',
    color: '#E63950',
    gradientColors: ['#E63950', '#B02E40'],
    charLimit: 300,
  },
  {
    id: 'bumble',
    name: 'Bumble',
    type: 'Dating',
    iconName: 'bee',
    color: '#FFC629',
    gradientColors: ['#FFD43B', '#FFC629'],
    charLimit: 300,
  },
  {
    id: 'tinder',
    name: 'Tinder',
    type: 'Dating',
    iconName: 'fire',
    color: '#FD5564',
    gradientColors: ['#FF7854', '#FD5564'],
    charLimit: 500,
  },
  {
    id: 'okcupid',
    name: 'OkCupid',
    type: 'Dating',
    iconName: 'heart-circle',
    color: '#5B0AE8',
    gradientColors: ['#8A2BE2', '#5B0AE8'],
    charLimit: 500,
  },
  {
    id: 'cmb',
    name: 'Coffee Meets Bagel',
    type: 'Dating',
    iconName: 'coffee-outline',
    color: '#7B3F61',
    gradientColors: ['#A85C7C', '#7B3F61'],
    charLimit: 280,
  },
  {
    id: 'pof',
    name: 'Plenty of Fish',
    type: 'Dating',
    iconName: 'fish',
    color: '#0099E5',
    gradientColors: ['#22B2FF', '#0099E5'],
    charLimit: 500,
  },
  {
    id: 'happn',
    name: 'Happn',
    type: 'Dating',
    iconName: 'map-marker-radius',
    color: '#00C2CB',
    gradientColors: ['#3CE0E8', '#00C2CB'],
    charLimit: 150,
  },

  // ── Social ────────────────────────────────────────
  {
    id: 'instagram',
    name: 'Instagram',
    type: 'Social',
    iconName: 'instagram',
    color: '#E1306C',
    gradientColors: ['#F77737', '#E1306C', '#833AB4'],
    charLimit: 150,
  },
  {
    id: 'twitter',
    name: 'X (Twitter)',
    type: 'Social',
    iconName: null,
    iconText: 'X',
    color: '#000000',
    gradientColors: ['#1a1a1a', '#000000'],
    charLimit: 160,
  },
  {
    id: 'threads',
    name: 'Threads',
    type: 'Social',
    iconName: 'at',
    color: '#000000',
    gradientColors: ['#333333', '#111111'],
    charLimit: 150,
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    type: 'Social',
    iconName: 'music-note',
    color: '#FF0050',
    gradientColors: ['#25F4EE', '#FE2C55'],
    charLimit: 80,
  },
  {
    id: 'youtube',
    name: 'YouTube',
    type: 'Social',
    iconName: 'youtube',
    color: '#FF0000',
    gradientColors: ['#FF0000', '#CC0000'],
    charLimit: 1000,
  },
  {
    id: 'facebook',
    name: 'Facebook',
    type: 'Social',
    iconName: 'facebook',
    color: '#1877F2',
    gradientColors: ['#2D88FF', '#1877F2'],
    charLimit: 101,
  },
  {
    id: 'snapchat',
    name: 'Snapchat',
    type: 'Social',
    iconName: 'snapchat',
    color: '#FFFC00',
    gradientColors: ['#FFFC00', '#F5D800'],
    charLimit: 150,
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    type: 'Social',
    iconName: 'pinterest',
    color: '#E60023',
    gradientColors: ['#FF2545', '#E60023'],
    charLimit: 160,
  },
  {
    id: 'telegram',
    name: 'Telegram',
    type: 'Social',
    iconName: 'send',
    color: '#2AABEE',
    gradientColors: ['#4AC7FF', '#2AABEE'],
    charLimit: 255,
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    type: 'Social',
    iconName: 'whatsapp',
    color: '#25D366',
    gradientColors: ['#25D366', '#128C7E'],
    charLimit: 139,
  },
  {
    id: 'discord',
    name: 'Discord',
    type: 'Social',
    iconName: 'forum',
    color: '#5865F2',
    gradientColors: ['#7289DA', '#5865F2'],
    charLimit: 190,
  },
  {
    id: 'reddit',
    name: 'Reddit',
    type: 'Social',
    iconName: 'reddit',
    color: '#FF4500',
    gradientColors: ['#FF6534', '#FF4500'],
    charLimit: 200,
  },
  {
    id: 'mastodon',
    name: 'Mastodon',
    type: 'Social',
    iconName: 'mastodon',
    color: '#6364FF',
    gradientColors: ['#8F8FFF', '#6364FF'],
    charLimit: 500,
  },
  {
    id: 'bereal',
    name: 'BeReal',
    type: 'Social',
    iconName: 'camera-outline',
    color: '#000000',
    gradientColors: ['#555555', '#000000'],
    charLimit: 100,
  },

  // ── Professional ─────────────────────────────────
  {
    id: 'linkedin',
    name: 'LinkedIn',
    type: 'Professional',
    iconName: 'linkedin',
    color: '#0A66C2',
    gradientColors: ['#0A66C2', '#064799'],
    charLimit: 2600,
  },
  {
    id: 'github',
    name: 'GitHub',
    type: 'Professional',
    iconName: 'github',
    color: '#ffffff',
    gradientColors: ['#4a4a4a', '#24292e'],
    charLimit: 160,
  },
  {
    id: 'substack',
    name: 'Substack',
    type: 'Professional',
    iconName: 'newspaper-variant-outline',
    color: '#FF6719',
    gradientColors: ['#FF8C42', '#FF6719'],
    charLimit: 280,
  },
  {
    id: 'medium',
    name: 'Medium',
    type: 'Professional',
    iconName: 'newspaper',
    color: '#000000',
    gradientColors: ['#555555', '#000000'],
    charLimit: 160,
  },
  {
    id: 'patreon',
    name: 'Patreon',
    type: 'Professional',
    iconName: 'patreon',
    color: '#FF424D',
    gradientColors: ['#FF6370', '#FF424D'],
    charLimit: 250,
  },
  {
    id: 'fiverr',
    name: 'Fiverr',
    type: 'Professional',
    iconName: 'briefcase-outline',
    color: '#1DBF73',
    gradientColors: ['#1DBF73', '#17a35e'],
    charLimit: 600,
  },

  // ── Others (Creative) ──────────────────────────────
  {
    id: 'spotify',
    name: 'Spotify',
    type: 'Creative',
    iconName: 'spotify',
    color: '#1DB954',
    gradientColors: ['#1DB954', '#158a3e'],
    charLimit: 1500,
  },
  {
    id: 'twitch',
    name: 'Twitch',
    type: 'Creative',
    iconName: 'twitch',
    color: '#9146FF',
    gradientColors: ['#B066FF', '#9146FF'],
    charLimit: 300,
  },
];

export const PLATFORM_BY_ID = Object.fromEntries(PLATFORMS.map((p) => [p.id, p]));
